added conditional 2 to the docker script
Topher2014/DockerScript pull request #18
Opened 2024-12-04 17:05 UTC by MonetCarriere

I took the conditional that was assigned to me and broke each command into it's own if statement following the convention of checking to see if it exists, echoing a statement if it does, and it if doesn't exist proceeding to get it.

2024-12-04 17:54 UTC, stephenlauck requested changes

2024-12-04 17:54 UTC, stephenlauck commented on dockerInstall.sh
>  sudo apt-get update
Use that apt-cache show approach on each package to know when to run apt update instead of running it blindly every time the script runs. This will slow down at a certain scale and provides no business value.

2024-12-04 17:54 UTC, stephenlauck commented on dockerInstall.sh
> +if dpkg -l | grep -q 'ca-certificates' && dpkg -l | grep -q 'curl'; then
I wouldn't stack packages, check each one individual if in apt-cache and if installed.

2024-12-04 18:48 UTC, MonetCarriere commented on dockerInstall.sh
> +if dpkg -l | grep -q 'ca-certificates' && dpkg -l | grep -q 'curl'; then
Okay 👍

2024-12-04 19:02 UTC, MonetCarriere commented on dockerInstall.sh
>  sudo apt-get update
My reasoning for doing it this way was that if I’m going to search through the package list for the **ca-certificates** and **curl** packages, then it made sense to update the package list first.

But I understand your point, and suspected you might suggest using the apt cache. ...I'll get on that  👍

2024-12-04 19:02 UTC, MonetCarriere commented on dockerInstall.sh
>  sudo apt-get update
My reasoning for doing it this way was that if I’m going to search through the package list for the **ca-certificates** and **curl** packages, then it made sense to update the package list first.

But I understand your point, and suspected you might suggest using the apt cache. ...I'll get on that  👍

2024-12-10 17:28 UTC, Topher2014 approved these changes

2024-12-10 17:31 UTC, merged

2024-12-11 03:28 UTC, stephenlauck commented on dockerInstall.sh
> +# See if apt-get exists. If so, update the repo.
Apt-get is assumed to be on the system if it's debian based so you don't need to check this.